version: "3"

volumes:
  postgres_data:

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      
  keycloak:
    image: ${ECR_URL}/keycloak
    environment:
      - DB_VENDOR
      - DB_ADDR
      - DB_DATABASE
      - DB_USER
      - DB_PASSWORD
      - DB_SCHEMA
      - KEYCLOAK_USER
      - KEYCLOAK_PASSWORD
      - KEYCLOAK_IMPORT
    ports:
      - 8080:8080
    depends_on:
      - postgres

  api:
    image: ${ECR_URL}/api:latest
    ports:
      - 8081:8081
    depends_on:
      - keycloak
    environment:
      - KEYCLOAK_URL
      - KEYCLOAK_USER
      - KEYCLOAK_PASSWORD
      - KEYCLOAK_CLIENT_ID
      - KEYCLOAK_CLIENT_SECRET
      - KEYCLOAK_REALM
