version: "3"

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    # image: quay.io/keycloak/keycloak:latest
    build: ./keycloak
    volumes:
      - ./keycloak/pucrs-cs-realm.json:/tmp/pucrs-cs-realm.json
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      KEYCLOAK_IMPORT: /tmp/pucrs-cs-realm.json
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8080:8080
    depends_on:
      - postgres
  api:
    image: openjdk:18-jdk-alpine3.13
    ports:
      - 8081:8081
    volumes:
      - ./build/libs/construcao-software-0.0.1-SNAPSHOT.jar:/tmp/app.jar
    entrypoint: sh -c "sleep 50 && cd /tmp && java -jar app.jar"
    depends_on:
      - keycloak
