version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - 8080:8080
    depends_on:
      - postgres
  api:
    build:
      context: .
      dockerfile: Dockerfile.keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - 8081:8081
    volumes:
      - ./keycloak-initial-setup.sh:/tmp/keycloak-initial-setup.sh
      - ./build/libs/construcao-software-0.0.1-SNAPSHOT.jar:/tmp/app.jar
    entrypoint: sh -c "sleep 60 && cd /tmp && ./keycloak-initial-setup.sh && java -jar app.jar"
            # entrypoint: [ "bash", "-c", "sleep 60 && cd /tmp && ./keycloak-initial-setup.sh && java -jar dockerdemo.jar"]
    depends_on:
      - keycloak
